version: 2.1
orbs:
  aws-s3: circleci/aws-s3@1.0.15
jobs:
  build:
    docker:
      - image: 'python:3-slim'
    steps:
      - checkout
      - run: pip install cfn-lint awscli
      - run: cfn-lint -t gitlab-runner-template.yml
      - aws-s3/copy:
          arguments: '--acl public-read'
          from: ./gitlab-runner-template.yml
          to: 's3://autoscaling-ec2-gitlab-runners-fargate/${CIRCLE_BRANCH}/gitlab-runner-template.yml'
    branches:
      only:
        - master
        - dev