version: 2.1
orbs:
  aws-s3: circleci/aws-s3@x.y
jobs:
  test:
    docker:
      - image: 'python:3-slim'
    steps:
      - checkout
      - run: pip install cfn-lint
      - run: cfn-lint -t gitlab-runner-template.yml
  deploy:
    docker:
      - image: 'python:3-slim'
    steps:
      - checkout
      - aws-s3/copy:
          arguments: '--acl public-read'
          from: ./gitlab-runner-template.yml
          to: 's3://my-s3-bucket-name'
          s3://autoscaling-ec2-gitlab-runners-fargate/${CIRCLE_BRANCH}/gitlab-runner-template.yml
